# These are supported funding model platforms

github: # Processing100DaysSketch
patreon: # Replace with a single Patreon username
open_collective: # Processing100DaysSketch
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://cdn.jsdelivr.net/gh/dabing1022/IMAGES_2023/2023/05/sponsor.png', 'https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzA5ODAwNzY0MQ==#wechat_redirect']
